services:
  db:
    image: postgres:15-alpine
    container_name: devops_rating_db
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_rating_api
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: devops_rating
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops_rating_frontend
    ports:
      - "80:80"
    depends_on:
      - api

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: devops_rating_tests
    environment:
      SMOKE_BASE_URL: http://api:8000
    profiles:
      - testing
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started


volumes:
  postgres_data:
